# Gemfile
gem_group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails'
  gem 'guard-bundler'
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'guard-migrate'
  gem "quiet_assets"
end

#gem_group :test do
#  gem 'capybara'
#end

gem_group :production do
  gem 'pg'
  gem 'rails_12factor'
end

#gem 'devise'
gem 'simple_form'
#gem 'kaminari'
#gem 'i18n_generators'

gem "twitter-bootstrap-rails"
gem "less-rails"
gem 'therubyracer'
gem 'carrierwave'
gem 'streamio-ffmpeg'

run_bundle # bundle install

generate 'rspec:install'
remove_dir 'test'

generate 'simple_form:install'
run 'guard init'

generate 'bootstrap:install'
generate 'bootstrap:layout application fixed'
generate 'rails g uploader video'

# App
generate(:scaffold, "article", "title:string", "video:string")
route "root to: 'articles#index'"

# DB
rake 'db:drop'
rake 'db:create'
rake 'db:migrate'

# .gitignore
file ".gitignore", <<-END
# See https://help.github.com/articles/ignoring-files for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile '~/.gitignore_global'

# Ignore bundler config.
/.bundle

# Ignore the default SQLite database.
/db/*.sqlite3
/db/*.sqlite3-journal

# Ignore all logfiles and tempfiles.
/log/*.log
/tmp

Gemfile.lock
coverage
doc/
spec/reports
test/tmp
.idea
reports
public/system
.DS_Store
END

# Git
git :init
git add: '.'
git commit: %Q{ -m 'Initial commit'}
